name=FreeRTOS_CJJ
version=0.1.0
author=Jo4096
maintainer=Jo4096
sentence=Libraries to make the usage of FreeRTOS safer (no direct void*, forgetting to free mutexes, no memory allocation)  and easier to use OOP style
paragraph=
category=Other
url=
architectures=*
depends=
includes=Kernel.hpp, Threads.hpp, ThreadArduino.hpp, ThreadRTOS.hpp, Mutex.hpp, LGuards.hpp, SafeQueues.hpp, Semaphores.hpp, EventGroups.hpp, SoftwareTimers.hpp, StreamBuffer.hpp, TaskNotification.hpp, SafeSerial.hpp, SafeWire.hpp, SafeSPI.hpp
