name=FreeRTOS_CJJ
version=0.1.5
author=Jo4096
maintainer=Jo4096
sentence=Libraries to make the usage of FreeRTOS safer (no direct void*, forgetting to free mutexes, no memory allocation)  and easier to use OOP style
paragraph=A C++ object-oriented abstraction layer for FreeRTOS that wraps tasks, mutexes (using RAII guards), queues, and semaphores. It eliminates raw void pointers, ensures type-safe IPC, and avoids dynamic memory allocation to comply with safety-critical embedded standards. Fully normalizes APIs across ESP32, RP2040, and AVR architectures.
category=Other
url=https://github.com/Jo4096/FreeRTOS_CJJ
architectures=*
depends=FreeRTOS
includes=Kernel.hpp, Threads.hpp, ThreadArduino.hpp, ThreadRTOS.hpp, Mutex.hpp, LGuards.hpp, SafeQueues.hpp, Semaphores.hpp, EventGroups.hpp, SoftwareTimers.hpp, StreamBuffer.hpp, TaskNotification.hpp, SafeSerial.hpp, SafeWire.hpp, SafeSPI.hpp, SafeRingBuffer.hpp
